---
# Example CloudflareZeroTrustTenant
# Replace values with your actual Cloudflare account details
apiVersion: cfzt.cloudflare.com/v1alpha1
kind: CloudflareZeroTrustTenant
metadata:
  name: prod-tenant
  namespace: default
spec:
  # Your Cloudflare account ID (32-character hex)
  accountId: "0123456789abcdef0123456789abcdef"
  
  # Your Cloudflare Tunnel ID (UUID format)
  tunnelId: "12345678-1234-1234-1234-123456789abc"
  
  # Optional: Your Cloudflare Zone ID (32-character hex)
  # zoneId: "0123456789abcdef0123456789abcdef"
  
  # Reference to Secret containing Cloudflare API token
  credentialRef:
    name: cloudflare-api-token
    key: token
  
  # Default values for managed resources
  defaults:
    sessionDuration: "24h"
    originService: "http://traefik.traefik.svc:80"

---
# Example Secret for Cloudflare API token
# Create this in your cluster with: kubectl create secret generic cloudflare-api-token --from-literal=token=YOUR_TOKEN
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: default
type: Opaque
stringData:
  # Replace with your actual Cloudflare API token
  # Token needs: Account.Cloudflare Tunnel:Edit, Account.Access:Edit
  token: "YOUR_CLOUDFLARE_API_TOKEN_HERE"
