---
# Example CloudflareZeroTrustTenant
# Replace values with your actual Cloudflare account details
apiVersion: cfzt.cloudflare.com/v1alpha1
kind: CloudflareZeroTrustTenant
metadata:
  name: prod-tenant
  namespace: default
spec:
  # Your Cloudflare account ID (32-character hex)
  accountId: "0123456789abcdef0123456789abcdef"
  
  # Your Cloudflare Tunnel ID (UUID format)
  tunnelId: "12345678-1234-1234-1234-123456789abc"
  
  # Optional: Your Cloudflare Zone ID (32-character hex)
  # zoneId: "0123456789abcdef0123456789abcdef"
  
  # Reference to Secret containing Cloudflare API token
  credentialRef:
    name: cloudflare-api-token
    key: token
  
  # Default values for managed resources
  defaults:
    # Session duration for Access Applications
    sessionDuration: "24h"
    
    # Default origin service URL
    # Scheme (http:// or https://) determines service type
    originService: "https://traefik.traefik.svc.cluster.local:443"
    
    # Optional: HTTP Host header to send to origin
    # httpHostHeader: "myapp.internal"
    
    # Enable HTTP to HTTPS redirect (default: true)
    httpRedirect: true
    
    # Origin TLS settings (for HTTPS origins)
    originTLS:
      # Disable TLS verification (useful for self-signed certs)
      noTLSVerify: true
      
      # Hostname cloudflared should expect from origin certificate (SNI)
      # If not set, uses the origin service hostname
      # originServerName: "traefik.traefik.svc.cluster.local"
      
      # Path to CA certificate for origin (if not Cloudflare-signed)
      # caPool: "/path/to/ca.pem"
      
      # Timeout for TLS handshake to origin (seconds)
      tlsTimeout: 10
      
      # Use HTTP/2 to origin (requires HTTPS)
      http2Origin: false
      
      # Automatically set SNI to match incoming request hostname
      matchSNIToHost: false

---
# Example Secret for Cloudflare API token
# Create this in your cluster with: kubectl create secret generic cloudflare-api-token --from-literal=token=YOUR_TOKEN
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: default
type: Opaque
stringData:
  # Replace with your actual Cloudflare API token
  # Token needs: Account.Cloudflare Tunnel:Edit, Account.Access:Edit
  token: "YOUR_CLOUDFLARE_API_TOKEN_HERE"
